// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: src/proto/movie.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price   float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	InStock bool    `protobuf:"varint,3,opt,name=inStock,proto3" json:"inStock,omitempty"`
}

func (x *MovieItem) Reset() {
	*x = MovieItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieItem) ProtoMessage() {}

func (x *MovieItem) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieItem.ProtoReflect.Descriptor instead.
func (*MovieItem) Descriptor() ([]byte, []int) {
	return file_src_proto_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MovieItem) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

type AddMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WasSaved bool  `protobuf:"varint,1,opt,name=wasSaved,proto3" json:"wasSaved,omitempty"`
	ItemId   int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (x *AddMovieResponse) Reset() {
	*x = AddMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMovieResponse) ProtoMessage() {}

func (x *AddMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMovieResponse.ProtoReflect.Descriptor instead.
func (*AddMovieResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_movie_proto_rawDescGZIP(), []int{1}
}

func (x *AddMovieResponse) GetWasSaved() bool {
	if x != nil {
		return x.WasSaved
	}
	return false
}

func (x *AddMovieResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type FetchMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FetchMovieRequest) Reset() {
	*x = FetchMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMovieRequest) ProtoMessage() {}

func (x *FetchMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMovieRequest.ProtoReflect.Descriptor instead.
func (*FetchMovieRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_movie_proto_rawDescGZIP(), []int{2}
}

func (x *FetchMovieRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_src_proto_movie_proto protoreflect.FileDescriptor

var file_src_proto_movie_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x4f,
	0x0a, 0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x22,
	0x46, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x61, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x32, 0x88, 0x01, 0x0a, 0x05, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x61,
	0x76, 0x65, 0x4e, 0x65, 0x77, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x10, 0x2e, 0x6d, 0x6f, 0x76,
	0x69, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x17, 0x2e, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x18, 0x2e,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x42, 0x31, 0x0a, 0x18, 0x69,
	0x6f, 0x2e, 0x67, 0x70, 0x72, 0x63, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x0a, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x5a, 0x09, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_movie_proto_rawDescOnce sync.Once
	file_src_proto_movie_proto_rawDescData = file_src_proto_movie_proto_rawDesc
)

func file_src_proto_movie_proto_rawDescGZIP() []byte {
	file_src_proto_movie_proto_rawDescOnce.Do(func() {
		file_src_proto_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_movie_proto_rawDescData)
	})
	return file_src_proto_movie_proto_rawDescData
}

var file_src_proto_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_movie_proto_goTypes = []interface{}{
	(*MovieItem)(nil),         // 0: movie.MovieItem
	(*AddMovieResponse)(nil),  // 1: movie.AddMovieResponse
	(*FetchMovieRequest)(nil), // 2: movie.FetchMovieRequest
}
var file_src_proto_movie_proto_depIdxs = []int32{
	0, // 0: movie.Movie.SaveNewMovie:input_type -> movie.MovieItem
	2, // 1: movie.Movie.FetchExistingMovie:input_type -> movie.FetchMovieRequest
	1, // 2: movie.Movie.SaveNewMovie:output_type -> movie.AddMovieResponse
	0, // 3: movie.Movie.FetchExistingMovie:output_type -> movie.MovieItem
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_movie_proto_init() }
func file_src_proto_movie_proto_init() {
	if File_src_proto_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_movie_proto_goTypes,
		DependencyIndexes: file_src_proto_movie_proto_depIdxs,
		MessageInfos:      file_src_proto_movie_proto_msgTypes,
	}.Build()
	File_src_proto_movie_proto = out.File
	file_src_proto_movie_proto_rawDesc = nil
	file_src_proto_movie_proto_goTypes = nil
	file_src_proto_movie_proto_depIdxs = nil
}
